// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRSSFeed(arg1) {
  return window['go']['main']['App']['AddRSSFeed'](arg1);
}

export function ExportFeeds() {
  return window['go']['main']['App']['ExportFeeds']();
}

export function FetchUpdates(arg1) {
  return window['go']['main']['App']['FetchUpdates'](arg1);
}

export function FetchUpdatesForAllFeeds() {
  return window['go']['main']['App']['FetchUpdatesForAllFeeds']();
}

export function GetFeeds() {
  return window['go']['main']['App']['GetFeeds']();
}

export function GetPost(arg1) {
  return window['go']['main']['App']['GetPost'](arg1);
}

export function GetPosts(arg1) {
  return window['go']['main']['App']['GetPosts'](arg1);
}

export function ImportFeeds() {
  return window['go']['main']['App']['ImportFeeds']();
}
